version: "3"

services:
  client:
    stdin_open: true
    container_name: nutritrack-ui
    build: ./server/client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - nutritrack

  server:
    build: ./server
    container_name: nutritrack-api
    env_file: docker.env
    ports:
      - "5000:5000"
    networks:
      - nutritrack
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: nutritrack-db
    ports:
      - "27017:27017"
    networks:
      - nutritrack
    volumes:
      - ./data:/data/db

networks:
  nutritrack:
    driver: bridge
