version: "3"

services:
  frontend:
    image: react-app
    stdin_open: true
    container_name: react-ui
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - nutritrack

  backend:
    image: api-server
    build: ./
    container_name: node-api
    ports:
      - "5000:5000"
    networks:
      - nutritrack
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - nutritrack
    volumes:
      - mongo-data:/data/db

networks:
  nutritrack:
    driver: bridge
volumes:
  mongo-data:
    driver: local
